// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDlHyFMBsNd9U5sc83PNZEF22CX6zPZsg',
    appId: '1:954737248617:web:da4e3b5850f98d10ac95f8',
    messagingSenderId: '954737248617',
    projectId: 'success-academy-5eed2',
    authDomain: 'success-academy-5eed2.firebaseapp.com',
    storageBucket: 'success-academy-5eed2.appspot.com',
    measurementId: 'G-KSXLK2CDGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7y0IQwuKEBp0-qpr6PT7I002v7ULnGDo',
    appId: '1:954737248617:android:4d9ba07e096a50dcac95f8',
    messagingSenderId: '954737248617',
    projectId: 'success-academy-5eed2',
    storageBucket: 'success-academy-5eed2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZPW9bzKi7J23iaJIrLoa0s3Wz74UqZ-o',
    appId: '1:954737248617:ios:139a5f1eb18d91cbac95f8',
    messagingSenderId: '954737248617',
    projectId: 'success-academy-5eed2',
    storageBucket: 'success-academy-5eed2.appspot.com',
    iosClientId: '954737248617-s72s7e9706tcupisl21ph0hek29oltgd.apps.googleusercontent.com',
    iosBundleId: 'com.successacademy.app',
  );
}
